services:
  mc-forever:
    image: itzg/minecraft-server:latest
    container_name: mc-forever
    ports:
      - "25565:25565"
      - "8123:8123"
      - "24455:24455/udp"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.1"
      ENABLE_RECON: "true"
      RCON_PASSWORD: "test"
      MEMORY: "8192M"
      MOTD: "Meteor Shower - Vanilla"
      USE_AIKAR_FLAGS: "true"
      USE_MEOWICE_FLAGS: "true"
      TZ: "UTC"
      DIFFICULTY: "3"
      ENABLE_COMMAND_BLOCK: "true"
      VIEW_DISTANCE: "16"
      SPAWN_PROTECTION: "0"
      # ENABLE_WHITELIST: "true"
      # WHITELIST: |-
      #   Mindstormman
      #   Liam73995
      #   GeeseMooseMeese
      #   Waven06
      #   0_Aster_0
      ALLOW_FLIGHT: "true"
      ONLINE_MODE: "true"
    volumes:
      - "./data:/data"
    restart: unless-stopped

  statcrafter:
    image: python:3.12-slim
    container_name: forever_statcrafter
    ports:
        - "5000:5000"
    volumes:
      - ./data:/data
    working_dir: /data
    depends_on:
      - mc-forever
    environment:
      SERVER_ADDRESS: mc-forever # uses the name of the other container
    command: >
        bash -c "
        set -e &&

        echo 'Installing system deps...' &&
        apt-get update &&
        apt-get install -y git &&

        cd /data &&
        git config --global --add safe.directory /data/MeteorShowerStats

        if [ ! -d MeteorShowerStats ]; then
            echo 'Cloning StatCrafter...' &&
            git clone https://github.com/Mindstormman06/MeteorShowerStats.git;
        else
            echo 'StatCrafter already exists';
        fi &&

        cd MeteorShowerStats &&
        git switch cyberschooled &&

        pip install --upgrade pip --root-user-action=ignore &&
        pip install -r requirements.txt --root-user-action=ignore &&

        echo 'Starting StatCrafter...' &&
        python -u app.py
        "
    restart: unless-stopped
